/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Mila business analysis API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface BusinessProfile {
    /** @minLength 1 */
    business_name: string;
    /** @minLength 1 */
    industry: string;
    /**
       * @minimum 1
       * @nullable
       */
    team_size?: number | null;
    tools?: string[];
    /** @nullable */
    workflows?: string | null;
    /** @nullable */
    repeated_tasks?: string | null;
    /** @nullable */
    time_wasters?: string | null;
    /** @nullable */
    top_priority?: string | null;
    /** @nullable */
    desired_outcome?: string | null;
    premium_active?: boolean;
    user_yes_for_automation?: boolean;
}
export interface AnalysisResult {
    summary: string;
    insights: string[];
    risks: string[];
    opportunities: string[];
    recommendations: string[];
    automation_allowed: boolean;
    note: string;
}
export interface ErrorResponse {
    error: string;
}
//# sourceMappingURL=api.schemas.d.ts.map